### ISSUE TITLE
Any hack to make this work with Camunda Cloud?

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-simple-tasklist#15]

**Comment by saig0** [comment]
Well, I guess partially. One part of the application uses the Hazelcast exporter which is not available in the Camunda cloud. However, the main job worker part should work. 

If you can pass the required parameters for the cloud (e.g. client id, client secret, cluster id) then it should poll the jobs from the Camunda cloud. 

What exactly do you want to do?
Running the app locally and get/complete jobs of type `user`?
